# Generated by Django 4.2.19 on 2025-03-02 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PerfumeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfumer', models.CharField(blank=True, db_column='Perfumer', max_length=50, null=True)),
                ('fragrance', models.CharField(blank=True, db_column='Fragrance', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfumer', models.CharField(blank=True, db_column='Perfumer', max_length=50, null=True)),
                ('fragrance', models.CharField(blank=True, db_column='Fragrance', max_length=50, null=True)),
                ('package', models.CharField(blank=True, db_column='Package', max_length=50, null=True)),
                ('bottle', models.CharField(blank=True, db_column='Bottle', max_length=50, null=True)),
                ('origin', models.CharField(blank=True, db_column='Origin', max_length=50, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('discount', models.FloatField(blank=True, db_column='Discount', max_length=50, null=True)),
                ('vat_back', models.FloatField(blank=True, db_column='VAT back', max_length=50, null=True)),
                ('purchase_currency', models.CharField(blank=True, db_column='Purchase Currency', max_length=10, null=True)),
                ('purch_exch_rate', models.FloatField(blank=True, db_column='Purch Exch Rate', null=True)),
                ('purchase_price_euro', models.FloatField(blank=True, db_column='Purchase Price (euro)', null=True)),
                ('purchase_date', models.DateField(blank=True, db_column='Purchase date', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=30, null=True)),
                ('sale_exch_rate', models.FloatField(blank=True, db_column='Sale Exch Rate', null=True)),
                ('sale_date', models.DateField(blank=True, db_column='Sale date', null=True)),
                ('sale_price', models.FloatField(blank=True, db_column='Sale price', null=True)),
                ('sale_price_eur', models.FloatField(blank=True, db_column='Sale price (EUR)', null=True)),
                ('earnings_eur', models.FloatField(blank=True, db_column='Earnings (EUR)', null=True)),
                ('premium', models.FloatField(blank=True, db_column='Premium_pct', null=True)),
                ('purchase_year', models.IntegerField(blank=True, db_column='purchase year', null=True)),
                ('purchase_month', models.IntegerField(blank=True, db_column='purchase month', null=True)),
                ('purchase_year_month', models.CharField(blank=True, db_column='purchase year_month', max_length=20, null=True)),
                ('sale_year', models.IntegerField(blank=True, db_column='sale year', null=True)),
                ('sale_month', models.IntegerField(blank=True, db_column='sale month', null=True)),
                ('sale_year_month', models.CharField(blank=True, db_column='sale year_month', max_length=20, null=True)),
                ('listed_price_ruble', models.FloatField(blank=True, db_column='listed_price_ruble', default=15000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfumePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfumes/')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PerfumeApp.perfumetransaction')),
            ],
        ),
    ]
