# Generated by Django 5.1.6 on 2025-03-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerfumeApp', '0002_fragrance_perfumetransaction_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumetransaction',
            name='listed_price_aed',
            field=models.FloatField(blank=True, db_column='listed_price_aed', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='perfumetransaction',
            name='listed_price_ruble',
            field=models.FloatField(blank=True, db_column='listed_price_ruble', default=0, null=True),
        ),
    ]
